name: CI

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches: [master]
  pull_request:
    paths-ignore:
      - '**/*.md'
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        node-version: [20.x]
        mongodb-version: [latest]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      MONGO_URI: mongodb://localhost:27017

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install --force

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Run tests
        run: npm test